name: Code Quality Assurance - Markdown

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - ".github/workflows/code-qa-markdown.yaml"
      - ".markdownlint.json"
      - ".markdownlintignore"
      - "package*.json"
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
      - ".github/workflows/code-qa-markdown.yaml"
      - ".markdownlint.json"
      - ".markdownlintignore"
      - "package*.json"

permissions:
  contents: read
jobs:
  code-quality-md:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Setup Node.js environment for TypeScript/JavaScript development
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      # Run Markdown specific checks
      - name: Run markdownlint
        run: npm run lint:markdown
